export enum TrainInfoTokenEnum {
	TRAIN_INFO_REPOSITORY_TOKEN = 'TRAIN_INFO_REPOSITORY_TOKEN',
	TRAIN_POSITION_INFO_REPOSITORY_TOKEN = 'TRAIN_POSITION_INFO_REPOSITORY_TOKEN',
	TRAIN_TYPE_INFO_REPOSITORY_TOKEN = 'TRAIN_TYPE_INFO_REPOSITORY_TOKEN',
	TRAIN_INFO_SERVICES_TOKEN = 'TRAIN_INFO_SERVICES_TOKEN',
}
